### ISSUE TITLE
Example code not correct

### ISSUE THREAD

**Issue by mickkn** [daPhoosa/CPPM-RX#2]
Hi, you should fix the Example code :)

/*
 * CPPM Test
 *
 * Connect receiver output to pin 3 on arduino micro
 * Displayes pulse width of each channel
 */

#define SERIAL_PORT Serial

#include <CPPM-RX.h>

void setup() {
  
  Serial.begin(115200);
  delay(1000);
  Serial.println("*** Program Start ***");
  
  StartCPPM(3);  // Digital pin 3 is interrupt 0

}

void loop() {
  
  delay(250);
  
  CPPM_display();
  
}

**Comment by daPhoosa** [comment]
fixed.
